create table
  public.rq1 (
    id bigint generated by default as identity not null,
    test_id text null,
    success boolean null,
    cloud_provider text null,
    region text null,
    run_time text null,
    function_name text null,
    allocated_memory bigint null,
    cpu_cores smallint null,
    execution_time double precision null,
    latency bigint null,
    was_cold_start boolean null,
    constraint rq1_pkey primary key (id)
  ) tablespace pg_default;