#! /bin/bash

# DATABASE CONFIG
SUPABASE_URL="YOUR_SUPABSE_URL"
SUPABASE_API_KEY="YOUR_SUPABASE_API_KEY"
SUPABASE_TABLE="rq1"

# PAYLOAD SIZES
SMALL_PAYLOAD=100
MEDIUM_PAYLOAD=200
LARGE_PAYLOAD=300

# ALL TEST URLS
## AWS LAMBDA FUNCTIONS
AWS_NODE_URL="YOUR_AWS_LAMBDA_NODE_URL"
AWS_PYTHON_URL="YOUR_AWS_LAMBDA_PYTHON_URL"
AWS_PYTHON_WITH_NUMPY_URL="YOUR_AWS_LAMBDA_PYTHON_WITH_NUMPY_URL"
AWS_JAVA_URL="YOUR_AWS_JAVA_URL"
## AZURE FUNCTIONS
AZURE_NODE_URL="YOUR_AZURE_NODE_URL"
AZURE_PYTHON_URL="YOUR_AZURE_PYTHON_URL"
AZURE_PYTHON_WITH_NUMPY_URL="YOUR_AZURE_PYTHON_WITH_NUMPY_URL" 
AZURE_JAVA_URL="YOUR_AZURE_JAVA_URL"
## GOOGLE CLOUD FUNCTIONS
GCP_NODE_URL="YOUR_GCP_NODE_URL"
GCP_PYTHON_URL="YOUR_GCP_PYTHON_URL"
GCP_PYTHON_WITH_NUMPY_URL="YOUR_GCP_PYTHON_WITH_NUMPY_URL"
GCP_JAVA_URL="YOUR_GCP_JAVA_URL"

# RUN AWS LAMBDA FUNCTIONS
## NODE
TEST_ID="rq1-aws-node-small" API_URL=$AWS_NODE_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-aws-node-medium" API_URL=$AWS_NODE_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-aws-node-large" API_URL=$AWS_NODE_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## PYTHON (only small payload)
TEST_ID="rq1-aws-python-small" API_URL=$AWS_PYTHON_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## PYTHON WITH NUMPY
TEST_ID="rq1-aws-python-with-numpy-small" API_URL=$AWS_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-aws-python-with-numpy-medium" API_URL=$AWS_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-aws-python-with-numpy-large" API_URL=$AWS_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## JAVA
TEST_ID="rq1-aws-java-small" API_URL=$AWS_JAVA_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-aws-java-medium" API_URL=$AWS_JAVA_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run rq1.js
TEST_ID="rq1-aws-java-large" API_URL=$AWS_JAVA_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
# RUN AZURE FUNCTIONS
## NODE
TEST_ID="rq1-azure-node-small" API_URL=$AZURE_NODE_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-azure-node-medium" API_URL=$AZURE_NODE_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-azure-node-large" API_URL=$AZURE_NODE_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## PYTHON (only small payload)
TEST_ID="rq1-azure-python-small" API_URL=$AZURE_PYTHON_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## PYTHON WITH NUMPY
TEST_ID="rq1-azure-python-with-numpy-small" API_URL=$AZURE_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-azure-python-with-numpy-medium" API_URL=$AZURE_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-azure-python-with-numpy-large" API_URL=$AZURE_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## JAVA
TEST_ID="rq1-azure-java-small" API_URL=$AZURE_JAVA_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-azure-java-medium" API_URL=$AZURE_JAVA_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-azure-java-large" API_URL=$AZURE_JAVA_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
# RUN GOOGLE CLOUD FUNCTIONS
## NODE
TEST_ID="rq1-gcp-node-small" API_URL=$GCP_NODE_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-gcp-node-medium" API_URL=$GCP_NODE_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-gcp-node-large" API_URL=$GCP_NODE_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## PYTHON (only small payload)
TEST_ID="rq1-gcp-python-small" API_URL=$GCP_PYTHON_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## PYTHON WITH NUMPY
TEST_ID="rq1-gcp-python-with-numpy-small" API_URL=$GCP_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-gcp-python-with-numpy-medium" API_URL=$GCP_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-gcp-python-with-numpy-large" API_URL=$GCP_PYTHON_WITH_NUMPY_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
## JAVA
TEST_ID="rq1-gcp-java-small" API_URL=$GCP_JAVA_URL PAYLOAD_SIZE=$SMALL_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-gcp-java-medium" API_URL=$GCP_JAVA_URL PAYLOAD_SIZE=$MEDIUM_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
TEST_ID="rq1-gcp-java-large" API_URL=$GCP_JAVA_URL PAYLOAD_SIZE=$LARGE_PAYLOAD SUPABASE_URL=$SUPABASE_URL SUPABASE_API_KEY=$SUPABASE_API_KEY SUPABASE_TABLE=$SUPABASE_TABLE k6 run k6-script.js
